### ISSUE TITLE
Protractor include in TypeScript

### ISSUE THREAD

**Issue by dmhalejr** [applitools/Eyes.Sdk.JavaScript#70]
Hello Applitools! 👋

Cross referenced here: https://github.com/applitools/Eyes.Selenium.JavaScript/issues/70

I wanted to ask about an implementation detail in your Typescript typings and wanted to get some clarity. I'm leveraging Typescript 3.3.3 and version 3.6.0 of the selenium-webdriver npm package only.

When I went to transpile my Typescript the eyes.selenium types told me it could not find the protractor npm package properly

Indeed in the types file it looks like the protractor flavors of By, ElementArrayFinder, and ElementFinder are being leveraged.

https://github.com/applitools/Eyes.Selenium.JavaScript/blob/master/typings/index.d.ts#L10

Is it possible to have two set of types published? @types/eyes.selenium and @types/eyes.selenium.protractor?

The workaround for the hiccup was just to add the protractor package into my automation project. A ton of bloat that is only leveraged for this one tool implementation.

Thanks for all you do! 🙇

**Comment by astappiev** [comment]
Should be fixed with applitools/Eyes.Sdk.JavaScript@5f459d8

I just removed protractor classes as they anyway cannot be implicitly used by a user. They are used via element and element.all globals.

**Comment by dylang** [comment]
Hi, thanks for making this fix quickly. Will this be published soon?

Thanks!

**Comment by astappiev** [comment]
Ping @danielputerman

**Comment by fescobar** [comment]
Hi @astappiev 
I would like to know if this issue is related to this change

I'm taking this repo as an example (it's not mine) but I can reproduce the error 
https://github.com/applitools/eyes-selenium-typescript-hello-world
If you execute
```
npm install
```
after that

```
npm run-script build
```

it will require protractor. Then I've added `protractor` to the package.json
```
"protractor":"5.4.2"
```
If you install and build again, it will work.

The issue is when updating the `eyes.selenium` version to the latest version (previous using 0.0.80).

```
    "eyes.selenium": "3.6.3",
```
If install and try to build again, it will appear this error:

```
> tsc -p tsconfig.json
node_modules/eyes.selenium/typings/index.d.ts(194,5): error TS2416: Property 'getScreenShot' in type 'Eyes' is not assignable to the same property in base type 'EyesBase'.
  Type '() => Promise<MutableImage>' is not assignable to type '() => Promise<EyesScreenshot>'.
    Type 'Promise<MutableImage>' is not assignable to type 'Promise<EyesScreenshot>'.
      Type 'MutableImage' is not assignable to type 'EyesScreenshot'.
        Property 'getImage' is missing in type 'MutableImage'.
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! eyes.selenium-example-ts@0.0.1 build: `tsc -p tsconfig.json`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the eyes.selenium-example-ts@0.0.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
```

Is this something that will be fixed with this change or do I need to create another ticket for this?

Thank you

**Comment by dmhalejr** [comment]
@fescobar This was an error I ran into myself and updated the types inside a reproducible example. Not saying run someone else's code but this would at least move the error out of the way for you. 

https://github.com/dmhalejr/applitools-reproducible-example/tree/master/scripts

Got this PR closed but maybe it actually didn't fix it. 
https://github.com/applitools/Eyes.Sdk.JavaScript/pull/71

**Comment by astappiev** [comment]
Hi @dmhalejr, @fescobar!

Thanks for your reply. @danielputerman finally released a new version this week.

Can you try it (eyes.selenium@3.6.5)?
Let me know if you still have the issues.

Best,
Oleh

**Comment by fescobar** [comment]
@astappiev @danielputerman 
I've recently tried with `3.6.5` version and it's working perfect.
Thanks guys, excellent work!

**Comment by fescobar** [comment]
Just one more question.
The method `eyes.getIsOpen()` was removed in typescript? it was deprecated?

**Comment by dmhalejr** [comment]
@fescobar Since you got it working in `3.6.5` I'll go ahead and close this issue. Sorry about your `eyes.getIsOpen()` issue. I'd say open up something else if it persists. 

Thanks folks!

**Comment by astappiev** [comment]
Hi @fescobar, the method was missing in typescript for an unknown reason. Will be added in next release.

**Comment by fescobar** [comment]
@astappiev no worries, it's not critical. Thanks.
